[package]
name = "rustxxx"
version = "0.1.0"
edition = "2024"

[features]
default = ["enable_tx", "enable_rx"]
enable_rx = []
enable_tx = []
audio_pass_test = []

[dependencies]
"wav_io" = "0.1"
"rustfft" = "6"
"realfft" = "3"
"libm" = "0.2.2"
"plotters" = "0.3.2"
"colorous" = "1.0.8"
crc = "3.4.0"
bitvec = "1.0.1"
bitstream-io = "4.9.0"
bitvec_helpers = "4.0.1"
trig = "0.4.0"
hilbert_transform = "0.1.2"
anyhow = "1.0.102"
hound = "3.5.1"
circular-buffer = "1.2.0"
thiserror = "2.0.18"
color-backtrace = "0.7.2"
clap = { version = "4.6.1", features = ["derive"] }
histogram = "1.2.0"
cpal = "0.17.3"
ringbuf = "0.5.0"
rubato = "3.0.0"
audioadapter-buffers = "3.0.0"
audioadapter = "3.0.0"
#transport = { path = "crates/transport" }
minifb = "0.28.0"
lazy_static = "1.5.0"

[[example]]
name = "ft8_streams"

[dev-dependencies]
ft8_message = { git = "https://github.com/nickr01/ft8_message" }
